server.port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo-project?createDatabaseIfNotExist=true
    username: root
    password: rootroot
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

spring.view.prefix: /WEB-INF/view/layouts
spring.view.suffix: .jspx

debug: true
trace: true
